# config.yaml

# General settings
general:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
  request_timeout: 10
  retry_attempts: 3
  delay_between_requests: 2  # Seconds

# Site-specific configurations
sites:

  humenglishfactcheck:
    base_url: "https://humenglish.com/fact-check/"
    start_urls:
      - "https://humenglish.com/fact-check/"
    delay: 2
    selectors: 
      single_post: "div.col-md-8 aside.wrapper__list__article div.card__post"
      post_title: "div.card__post__title h5 a::text"
      post_link: "div.card__post__title h5 a::attr(href)"
      post_date: "span.text-dark::text"
      exerpt: "div.card__post__title p::text" 
      post_image: "div.card__post__transition img::attr(data-lazy-src)"
      content: "div[id*='post_content'] p::text"
      label: "//p[strong[contains(text(), 'DW fact check')]]/text()"
      next_page: "div.pagination-area a.next::attr(href)"

  sochfactcheck:
    base_url: "https://www.sochfactcheck.com/"
    start_urls:
      - "https://www.sochfactcheck.com/wp-admin/admin-ajax.php"
    delay: 2
    selectors:
      single_post: 'div.article-box'
      post_title: 'div.article-box div.article-title-wrap div.title h6 a::text'
      post_link: "div.article-box div.article-title-wrap div.title h6 a::attr(href)"
      post_image: 'div.article-box div.featured-image figure a img::attr(src)'
      post_date: "div.article-box div.article-title-wrap div.article-meta div.article-date::text"
      post_cat: "div.article-box div.article-title-wrap div.article-meta div.article-cat a::text"
      content: "div.blog_detail_description p *::text"
      author: "div.blog_author_name a::text"

  pakiverify:
    base_url: "https://pak.i-verify.org/"
    start_urls:
      - "https://pak.i-verify.org/"
    delay: 2
    selectors:
      single_post: 'div.premium-blog-post-container'
      post_title: 'h2.premium-blog-entry-title a::text'
      post_date: 'div.premium-blog-post-time span::text'
      post_link: 'h2.premium-blog-entry-title a::attr(href)'
      post_image: 'div.premium-blog-thumbnail-container img::attr(src)'
      label: 'ul.post-categories li a::text'
      content: 'div.elementor-widget-wrap h3::text, div.elementor-widget-wrap p::text'
      author: 'span.elementor-heading-title::text'
      next_page: 'a.next.page-numbers::attr(href)'
  
  geofactcheck:
    base_url: "https://www.geo.tv/category/geo-fact-check"
    start_urls:
      - "https://www.geo.tv/category/geo-fact-check/more_news"
    delay: 2
    selectors:
      single_post: 'div.card'
      post_title: 'div.card-body a.text-body::text'
      post_date: 'span.date::text'
      post_link: 'div.card-body a.text-body::attr(href)'
      post_image: 'img.card-img-top::attr(src)'
      content: 'div.story-detail p::text'
      author: '//div[@class="author_title_img"][2]/a/text()'

  thefridaytimesfactcheck:
    base_url: "https://thefridaytimes.com/fact-check"
    start_urls:
      - "https://thefridaytimes.com/ajax_post_pagination"
    delay: 2
    selectors:
      single_post: 'article.zm-post-lay-a1'
      post_title: 'h2.zm-post-title a::text'
      post_link: 'h2.zm-post-title a::attr(href)'
      post_image: 'div.top-center::attr(alt)'
      post_date: 'ul.zm-post-meta-date span::text'
      content: 'div.zm-post-custom-content p::text'

  geonews:
    base_url: "https://www.geo.tv/latest-news"
    start_urls:
      - "https://www.geo.tv/latest-news"
    delay: 2
    selectors:
      single_post: 'div.list'
      post_title: 'div.entry-title h2::text'
      post_link: 'li.border-box a::attr(href)'
      post_image: 'div.medium-insert-images.ui-sortable figure[contenteditable="false"] img::attr(src)'
      post_date: 'p.post-date-time::text'
      author: 'span.author_agency::text'
      content: 'div.story-area p::text'
  
  snopes:
    base_url: "https://www.snopes.com/fact-check/"
    start_urls:
      - "https://www.snopes.com/fact-check/"
    delay: 5
    selectors:
      single_post: 'a.outer_article_link_wrapper'
      post_title: 'h3.article_title::text'
      post_link: 'a.outer_article_link_wrapper::attr(href)'
      post_date: 'span.article_date::text'
      post_image: 'img.lazy-image::attr(data-src)'
      author: 'span.author_name::text'
      label: 'div.rating_title_wrap::text'
      content: 'article#article-content > p::text'
      next_page: 'a.next-button::attr(href)'

  politifact:
    base_url: "https://www.politifact.com/factchecks/list/"
    start_urls:
      - "https://www.politifact.com/factchecks/list/"
    delay: 5
    selectors:
      single_post: 'div.m-statement__content'
      post_title: 'div.m-statement__quote a::text'
      label: 'img::attr(alt)'
      post_link: 'div.m-statement__quote a::attr(href)'
      post_date: 'span.m-author__date::text'
      author: 'div.m-author__content a::text'
      post_image: 'article.m-textblock p img::attr(src)'
      content: 'article.m-textblock p::text'
      
      next_page: '//li/a[text()="Next"]/@href'
  
  tribune:
      base_url: "https://tribune.com.pk/latest"
      start_urls:
        - "https://tribune.com.pk/latest"
      delay: 2
      selectors:
        single_post: 'ul.listing-page li div.row'
        post_title: 'h2.title-heading::text'
        post_date: 'div.left-authorbox span::text'
        post_link: 'a::attr(href)'
        post_image: 'div.featured-image-global img::attr(src)'
        content: 'div.storypage-rightside p::text'
        catagory: 'div.left-authorbox span a::text'
        next_page: 'a.page-link::attr(href)'

  reuters:
    base_url: "https://www.reuters.com/fact-check/"
    start_urls:
      - "https://www.reuters.com/fact-check/"
    delay: 2
    selectors: 
      single_post: 'li.story-card__tpl-common__1Q7br'
      post_title: 'div.title__title__29EfZ span::text'
      post_date: 'div.kicker-date__kicker-date__2VBU4 time::text'
      exerpt: 'li.story-card__tpl-common__1Q7br p::text'
      post_link: 'div.title__title__29EfZ a::attr(href)'
      post_image: 'div.styles__image-container__3hkY5 img::attr(src)'
      label: 'div[data-testid^="paragraph-"]::text'
      content: 'div.article-body__content__17Yit *::text'
      author: 'div.info-content__author-date__1Epi_ a::text'

  dawn:
    base_url: "https://www.dawn.com/latest-news/{date}"
    start_urls:
      - "https://www.dawn.com/latest-news"
    delay: 2
    selectors: 
      single_post: "article.story"
      post_title: "h2.story__title a::text"
      author: "div.my-3 span.story__byline a.story__byline__link::text"
      post_date: "span.story__time span.timestamp--published span.timestamp--date::text"
      post_link: "h2.story__title a::attr(href)"
      post_image: "div.media__item img::attr(src)"
      content: "div.story__content p::text"

  dwfactcheck:
    base_url: "https://www.dw.com/en/fact-check/t-56584214/page-1"
    start_urls:
      - "https://www.dw.com/en/fact-check/t-56584214/page-1"
    delay: 2
    selectors: 
      single_post: "div.teaser-wrap"
      post_title: "div.teaser-data h3 a::text"
      post_link: "div.teaser-data h3 a::attr(href)"
      post_date: "span.date-time time::text"
      exerpt: "div.s6kxfng a::text"
      post_image: "div.teaser-image-wrap img::attr(src)"
      category: "span.kicker::text"
      author: "div.author-details span a::text"
      content: "div.cc0m0op p::text"
      label: "//p[strong[contains(text(), 'DW Fact check')]]/text()"
      next_page: "div.sp605kw a.next::attr(href)"
      
  brecorder:
    base_url: "https://www.brecorder.com/latest-news"
    start_urls:
      - "https://www.brecorder.com/latest-news"
    selectors: 
      single_post: "div.flex article.story div.block"
      post_title: "h2.story__title a::text"
      post_link: "h2.story__title a::attr(href)"
      category: "span.badge a span::text"
      exerpt: "div.story__excerpt::text" 
      post_image: "figure.media div.media__item a picture img::attr(src)"
      content: "div.story__content p::text"
      author: "a.story__byline__link::text"
      post_date: "span.story__time span.timeago::attr(title)"

  dailytimes:
    base_url: "https://dailytimes.com.pk/tag/latest/"
    start_urls:
     - "https://dailytimes.com.pk/tag/latest/"
    selectors:
      single_post: "main.content article.type-post"
      post_title: "header.entry-header h2.entry-title a.entry-title-link::text"
      exerpt: "div.entry-content p::text"
      post_link: "header.entry-header h2.entry-title a.entry-title-link::attr(href)"
      post_image: "a.entry-image-link img::attr(data-lazy-src)"
      author: "p.author-links a.author-name::text"
      content: "div.entry-content P::text"
      post_date: "p.post-date time.entry-time::text"
      next_page: "div.pagination-next a::attr(href)"

  factcheckorg:
    base_url: "https://www.factcheck.org/"
    start_urls:
      - "https://www.factcheck.org/"
    selectors: 
      single_post: "main.site-main article.type-post"
      post_title: "h3.entry-title a::text"
      post_link: "h3.entry-title a::attr(href)"
      exerpt: "div.entry-content p::text" 
      post_image: "div.col-12 img::attr(src)"
      content: "div.content-area p::text"
      author: "div.entry-meta a::text"
      post_date: "div.entry-meta::text"
      next_page: "//li[contains(@class, 'page-item-next')]//a/@href"


  aljazeera:
    base_url: "https://www.aljazeera.com/sports/"
    start_urls:
      - "https://www.aljazeera.com/sports/"
    delay: 2
    selectors: 
      single_post: "article.gc--type-post"
      post_title: "article.gc--type-post h3.gc__title a span::text"
      post_link: "article.gc--type-post h3.gc__title a::attr(href)"
      exerpt: "div.gc__body-wrap div.gc__excerpt p::text" 
      post_image: "div.col-12 img::attr(src)"
      content: "div.wysiwyg--all-content p::text"
      post_date: "div.date-simple span.screen-reader-text::text"
      #next_page: "//li[contains(@class, 'page-item-next')]//a/@href"
     


  dunyanews: 
    base_url: "https://dunyanews.tv/en/Pakistan"
    start_urls:
      - "https://dunyanews.tv/en/Pakistan"
    selectors:
      single_post: "div.container div.row div.dunya-border-top"
      post_title: "h3.media__title a::text"
      post_link: "h3.media__title a::attr(href)"
      post_image: "div.media__image a picture img::attr(src)"
      post_date: "time.publish-time::attr(datetime)"
      content: "article p::text"


  humenglish:
    base_url: "https://humenglish.com/latest/"
    start_urls:
      - "https://humenglish.com/latest/"
    selectors:
      single_post: "div.container div.row div.col-md-8 aside.wrapper__list__article div.card__post"
      post_title: "div.card__post__title h5 a.truncate::text"
      post_link: "div.card__post__title h5 a.truncate::attr(href)"
      exerpt: "div.card__post__title p:nth-of-type(2)::text"
      post_image: "div.card__post__transition a img::attr(data-lazy-src)"
      post_date: "li.list-inline-item span.text-dark::text"
      content: "div[id*='post_content'] p::text"
      author: "li.list-inline-item span a::text"
      next_page: "a.next::attr(href)"


  jang:
    base_url: "https://jang.com.pk/en/latest"
    start_urls:
      - "https://jang.com.pk/en/latest"
    selectors: 
      single_post: "div.rt-left-sidebar-sapcer-5 div.post-list-style-4 div.post-item"
      post_title: "div.post-item div.rt-post div.post-content div.post-title a::text"
      post_link: "div.post-item div.rt-post div.post-content div.post-title a::attr(href)"
      exerpt: "div.post-content p.my-2::text"
      post_image: "div.post-img a img::attr(src)"
      author: "div.post-meta ul li span span::text"
      content: "div.detail_content_area div.post-body p::text"
      post_date: "div.post-meta span.rt-meta::text" 
      category: "div.post-header div.catName a::text"


  thenation:
    base_url: "https://www.nation.com.pk/latest"
    start_urls:
      - "https://www.nation.com.pk/ajax_post_pagination"
    selectors:
      single_post: "div.jeg_posts_wrap div.jeg_posts div.row div.col-lg-4"
      post_title: "div.jeg_postblock_content h3.jeg_post_title a::text"
      post_link: "div.jeg_postblock_content h3.jeg_post_title a::attr(href)"
      post_image: "div.jeg_thumb a div.thumbnail-container div.top-center::attr(style)"
      author: "div.jeg_meta_author a::text"
      content: "div.content-inner p::text"
      post_date: "div.jeg_meta_date::text"


  pakistantoday:
    base_url: "https://www.pakistantoday.com.pk/category/national/"
    start_urls:
      - "https://www.pakistantoday.com.pk/wp-admin/admin-ajax.php?td_theme_name=Newspaper&v=12.1.1"
    selectors:
      single_post: "div.td_module_10"
      post_title: "h3.entry-title a::attr(title)"
      post_link: "div.td-module-thumb a::attr(href)"
      post_image: "div.td-module-thumb a.td-image-wrap img.entry-thumb::attr(src)"
      exerpt: "div.td-excerpt::text"
      author: "div.tdb-author-name-wrap a.tdb-author-name::text"
      content: "div.tdb-block-inner p::text"
      post_date: "div.tdb-block-inner time.entry-date::text"

  thehindu:
    base_url: "https://www.thehindu.com/news/international/"
    start_urls:
      - "https://www.thehindu.com/news/international/?page=1"
    selectors:
      single_post: "div.row-element"
      post_title: "div.right-content h3.title a::text"
      post_link: "div.right-content h3.title a::attr(href)"
      post_image: "div.picture img::attr(data-src-template)"
      exerpt: "h2.sub-title::text"
      author: "div.author-name a::text"
      next_page: "li.page-item.next a.page-link.next::attr(href)"
      post_date: "div.update-publish-time span::text"

  samaatv:
    base_url: "https://www.samaa.tv/latest-news"
    start_urls:
      - "https://www.samaa.tv/latest-news"
    selectors:
      single_post: "section.story-section div.story-columns div.row div.col-12"
      post_title: "article.story-article div.text h3 a::text"
      post_link: "article.story-article div.text h3 a::attr(href)"
      post_image: "div.img-frame a img::attr(data-src)"
      exerpt: "div.text p::text"
      author: "div.col-7 strong.h4 a::text"
      post_date: "div.col-7 time::attr(datetime)"
      content: "div.article-content p::text"
      next_page: "ul.pagination li.page-item a[rel='next']::attr(href)"

  arynews:
    base_url: 
      - "https://arynews.tv/category/pakistan/"
      - "https://arynews.tv/category/international/"
      - "https://arynews.tv/category/business/"
      - "https://arynews.tv/category/sports/"
      - "https://arynews.tv/category/sci-techno/"
      - "https://arynews.tv/category/lifestyle/"
      - "https://arynews.tv/category/health-2/"
      - "https://arynews.tv/category/off-beat/"
      - "https://arynews.tv/category/latest-blogs/"
      - "https://arynews.tv/category/multimedia-stories/"
    start_urls:
      - "https://arynews.tv/wp-admin/admin-ajax.php?td_theme_name=Newspaper&v=12.6.2"
    selectors:
      single_post: "div.tdb_module_loop.td_module_wrap.td-animation-stack.td-cpt-post"
      post_title: "div.td-module-meta-info h3.entry-title a::text"
      post_link: "div.td-module-meta-info h3.entry-title a::attr(href)"
      post_image: "div.td-image-container div.td-module-thumb a span::attr(style)"
      author: "div.tdb-author-name-wrap a.tdb-author-name::text"
      post_date: "div.tdb-block-inner div.tdb-head-date-txt::text"
      exerpt: "div.tdb-block-inner p strong::text"
      content: "div.tdb-block-inner p::text"

  bbc:
    base_url: "https://www.bbc.com/news/world"
    start_urls:
      - "https://www.bbc.com/news/world"
    selectors:
      single_post: 'div[data-testid="liverpool-card"]'
      post_title: "div.sc-8ea7699c-0 h2.sc-8ea7699c-3::text"
      post_link: "div.sc-c6f6255e-0 a::attr(href)"
      exerpt: "p.sc-ae29827d-0::text"
      country: "div.sc-6fba5bd4-0 span.bHkTZK::text"
      post_date: "div.sc-b42e7a8f-1 time.sc-b42e7a8f-2::text"
      content: "div.sc-18fde0d6-0 p.sc-eb7bd5f6-0::text"

  nytimes:
    base_url: "https://www.nytimes.com/international/section/world"
    start_urls:
      - "https://www.nytimes.com/international/section/world"
    selectors:
      single_post: 'div.css-13mho3u div.css-14ee9cx'
      post_title: "div.sc-8ea7699c-0 h2.sc-8ea7699c-3::text"
      post_link: "div.sc-c6f6255e-0 a::attr(href)"
      exerpt: "p.sc-ae29827d-0::text"
      country: "div.sc-6fba5bd4-0 span.bHkTZK::text"
      post_date: "div.sc-b42e7a8f-1 time.sc-b42e7a8f-2::text"
      content: "div.sc-18fde0d6-0 p.sc-eb7bd5f6-0::text"

  thenews:
    base_url: 
      - "https://www.thenews.com.pk/latest/category/national"
      - "https://www.thenews.com.pk/latest/category/sports"
      - "https://www.thenews.com.pk/latest/category/world"
      - "https://www.thenews.com.pk/latest-stories"
    start_urls:
      - "https://www.thenews.com.pk/latest/category/national"
      - "https://www.thenews.com.pk/latest/category/sports"
      - "https://www.thenews.com.pk/latest/category/world"
      - "https://www.thenews.com.pk/latest-stories"
      - "https://www.thenews.com.pk/latest/category/business"
      - "https://www.thenews.com.pk/latest/category/entertainment"
      - "https://www.thenews.com.pk/latest/category/sci-tech"
      - "https://www.thenews.com.pk/latest/category/health"
    selectors:
      latest_stories:
        single_post: 'div.detail-content div.detail-center div.writter-list-item ul li div.writter-list-item-story'
        post_title: 'div.latest-right h2 a::text'
        post_link: 'div.latest-right h2 a::attr(href)'
        exerpt: 'div.latest-right p::text'
        post_image: 'div.writter-list-item-story a.latest-page-img img::attr(src)'
        author: '//div[@class="category-source"]/span/following-sibling::text()'
        author2: 'div.category-source span.open-section::text'
        post_date: 'div.category-date::text'
        content: 'div.story-detail p::text'
      business:
        single_post: 'div.container div.col-sm-12 div.new_category div.col-sm-6 div.most-popular-list'
        post_title: 'div.heading-cat a.open-section::attr(title)'
        post_link: 'div.heading-cat a.open-section::attr(href)'
        post_image: 'div.news-pic a img::attr(data-src)'
        author: '//div[@class="category-source"]/span/following-sibling::text()'
        post_date: 'div.category-date::text'
        content: 'div.story-detail p::text'

  bolnews:
    base_url: "https://www.bolnews.com/politics/"
    start_urls:
      - "https://www.bolnews.com/wp-admin/admin-ajax.php"
    selectors:
      single_post: 'div.col-lg-6'
      post_title: 'div.col-lg-6 div.post-box div.post-content h6.title::text'
      post_link: 'div.col-lg-6 div.post-box a::attr(href)'
      post_image: 'div.col-lg-6 div.post-box div.post-frame img::attr(src)'
      author: 'div.figure-wrap figcaption h6.mb-0 a::text'
      post_date: 'div.figure-wrap div.post-date p span.date::text'
      content: 'div.typo-txt p::text'

      #section.stripe-bottom-30 div.container div.row div.col-lg-8 div.row

# Storage settings
storage:
  method: "database"  # or "file"
  database:
    type: "sqlite"
    name: "scraped_data.db"
  file:
    format: "json"
    directory: "data/raw"

# Logging settings - defined in the settings.py file
#logging:
#  level: "INFO"
#  file: "logs/scraper.log"